name: Spellcheck

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: CSpell
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: ""
          check_dot_files: false
          inline: warning
          fail_on_error: false
          show_files: true
          incremental_files_only: true
          comment: true
          comment_on_same_line: true
          comment_fail_on_error: false
          exclude: "**/node_modules/**"
          language: en
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        if: steps.spellcheck.outputs.comment_added == 'true'
        with:
          message: "CSpell check found issues in the following files:\n\n${{ steps.spellcheck.outputs.comment }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
