name: Spellcheck

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: CSpell
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: "**"
          check_dot_files: false
          inline: warning
          incremental_files_only: true
          root: "."
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ failure() }}
        with:
          message: |
            There were spelling errors found in the code changes. Please fix the errors before merging.
            ```
            ${{ steps.CSpell.outputs.errors }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
