name: CSpell Check

on: [pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v2
        with:
          files: ""
          check_dot_files: explicit
          inline: warning
          strict: true
          incremental_files_only: true
